server:
  port: 19090
spring:
  activiti:
    check-process-definitions: false
  application:
    name: resource
management:
  security:
    enabled: false
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#数据源配置
first:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/e-procurement?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20	
    filters: config,stat,log4j2
    connectionProperties=druid.stat.mergeSql: true;druid.stat.slowSqlMillis=5000
#生成主键服务   
snowflakeidworker:
  workerid: 11111111111
  datacenterid: 222222222222
mybatis-plus:
  mapper-locations: classpath*:com/zero/**/*Mapper.xml,classpath*:com/zero/**/*.mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zero.**.pojo,com.zero.**.pojo.**.dto,com.zero.**.pojo.**.po,com.zero.**.domain.po,com.zero.**.domain.dto
  global-config:
    db-config:
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#自定义参数
SMS4: 1122334455667788